/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package de.qualersoft.jmeter.gradleplugin

import java.io.File
import org.junit.jupiter.api.Test
import kotlin.test.assertTrue

/**
 * A simple functional test for the 'de.qualersoft.jmeter' plugin.
 */
class JMeterPluginFunctionalTest : JMeterPluginFunctionalTestBase() {

  override fun rootFolder(): String? {
    val fa = getFolderAction
    return if (null == fa) null else fa()
  }

  var getFolderAction: (() -> String?)? = null

  @Test
  @KotlinTag
  fun `register a run task in kotlin dsl`() {
    // Setup the test build
    getFolderAction = { "runTest" }

    val runner = setupKotlinTest("default_build")
      .withArguments("tasks")

    copyJmxToDefaultLocation()

    val result = runner.build()

    assertTrue(result.output.contains("runTest"))
  }

  @Test
  @GroovyTag
  fun `register a run task in groovy dsl`() {
    // Setup the test build
    getFolderAction = { "runTest" }

    val runner = setupKotlinTest("default_build")
      .withArguments("tasks")

    copyJmxToDefaultLocation()

    val result = runner.build()

    assertTrue(result.output.contains("runTest"))
  }

  fun copyJmxToDefaultLocation() {
    val destFldr = testProjectDir.newFolder("./src/test/jmeter")
    destFldr.mkdirs()
    val resource = File(JMeterPluginFunctionalTest::class.java.classLoader.getResource("Test.jmx")!!.file)
    val destFile = destFldr.resolve(resource.name)
    resource.copyTo(destFile)
  }
}
