= jmeter-gradle-plugin
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
ifndef::env-github[]
:icons: font
endif::[]
:jm_tm:     https://jmeter.apache.org/[JMeter(TM),window=_blank]
:jm_cli:    https://jmeter.apache.org/usermanual/get-started.html#override
:toc: preamble

Gradle plugin to integrate {jm_tm} tests into the gradle ecosystem. +
This plugin arose from the need of a simple to start, but easy to customize plugin. The current available plugins are either hardwired to older {jm_tm} version or configuration is not so well documented.

== Usage
=== Applying the plugin
.Kotlin DSL
[%collapsible%open]
====
[source,kotlin]
----
plugins {
  id("de.qualersoft.jmeter") version "<latest>"
}
----
====

.Groovy DSL
[%collapsible]
====
[source,groovy]
----
plugins {
  id 'de.qualersoft.jmeter' version '<latest>'
}
----
====

=== Customization
The easiest way to customize the plugin is via its `jmeter` extension. +
The extension offers the following properties
[source,kotlin]
----
jmeter {
  jmxRootDir // <.>
  resultDir // <.>
  reportDir // <.>
  jmeterProperties // <.>
  globalPropertiesFile // <.>
  globalProperties // <.>
  maxHeap // <.>
  jvmArgs //<.>
}
----
[%collapsible]
====
<1> used to search for jmx files. +
Defaults to src/test/jmeter
<2> directory to which the jtl-files will be written. +
Defaults to <buildDir>/test-results/jmeter
<3> Root directory where to put the reports +
Defaults to <buildDir>/reports/jmeter
<4> [Optional] custom properties send to the local JMeter only. (for details refer to the {jm_cli}[JMeter documentation])
<5> [Optional] custom properties file send to all remote servers (for details refer to the {jm_cli}[JMeter documentation])
<6> [Optional] single key-value properties send to all remote server (for details refer to the {jm_cli}[JMeter documentation])
<7> [Optional] Specifies the maximum heap size the JVM process will start with.
<8> [Optional] additional JVM arguments that will be passed to the jvm directly.
====
These configurations will be applied to all tasks (where appropriate) and can be overridden or extended on a per task base.

== Quickstarter
[IMPORTANT,title=Important]
To use the quickstarter you must have gradle installed and available on your path

=== Running a jmeter-test
1. In a folder of your choice (referred to as `root`), execute:
+
[source,shell script]
----
root> gradle wrapper init
----
This brings up the setup. We are going to create a `basic` project and using `Kotlin` as build script DSL.
2. Create the following folder structure (gradle stuff from 1. left out)
+
[source]
----
root
├── src
│   └── test
│       └── jmeter
│           └── test.jmx <.>
└── build.gradle.kts <.>
----
<1> default folder for jmx-files is `src/test/jmeter`
<2> build.gradle.kts is generated by gradle we need it in next step.
3. Put the following into `build.gradle.kts`
+
[source,kotlin]
----
import de.qualersoft.jmeter.gradleplugin.task.* // <.>

plugins {
  id("de.qualersoft.jmeter") version "<latest>" // <.>
}

repositories {
  mavenCentral() // <.>
}

tasks {
  register<JMeterRunTask>("runJMeter") { // <.>
    jmxFile.set("test.jmx") // <.>
  }
}
----
<1> Import `task` package. (to save some typing later on 😋)
<2> Apply the plugin. (Don't forget to correct the version 😉)
<3> We need a repository to retrieve jmeter-library. `mavenCentral` should work in almost any case.
<4> Register a run-task and give it a name (if we wouldn't had imported the `task` package in (1), we would have to use the full qualified path)
<5> Configure the task to use our test.jmx file under `src/test/jmeter`
4. Run it by opening a cli of your choice in `root`
+
[source, shell script]
----
root> ./gradlew runJMeter
----
+
[source, shell script,title=Output]
----
...
Starting standalone test @ Sat Sep 04 18:53:51 CEST 2021 (1630774431340)
Waiting for possible Shutdown/StopTestNow/HeapDump/ThreadDump message on port 4445
Warning: Nashorn engine is planned to be removed from a future JDK release
summary =     30 in 00:00:03 =   10,0/s Avg:   206 Min:   108 Max:   345 Err:     2 (6,67%)
Tidying up ...    @ Sat Sep 04 18:53:55 CEST 2021 (1630774435185)
... end of run

BUILD SUCCESSFUL in 15s
1 actionable task: 1 executed
----

👏 Congratulations, you run your first jmeter script with this plugin. +
🎉 4 steps, that's it. Simple, wasn't it?

=== Generating a report
After you successfully run your first jmeter script, you might want to have a report showing some nice carts and stats.

No problem, just:

1. add the following to your `build.gradel.kts` s `task` section
+
[source,kotlin]
----
tasks {
  register<JMeterRunTask>("runJMeter") {
    jmxFile.set("test.jmx")
  }

  register<JMeterReportTask>("jmeterReport") { // <.>
    jmxFile.set("test.jmx") // <.>
  }
}
----
<1> registering a `JMeterReportTask` task (remember the include? Now it pays off 😊)
<2> by pointing it to our `jmx` file the plugin knows where to find everything

2. back in CLI run
+
[source, shell script]
----
root> gradlew jmeterReport
----
This generates the report under `build/reports/jmeter/Test`
[NOTE,title=Note]
The directory 'Test' is retrieved from the jmx-file's name.

🎉 Voila, just 2 steps to get a report.

The `runJMeter` task must be executed before. There are two ways you can get it in one rush.

1. Declare a `dependsOn` in report task
+
[source,kotlin]
----
register<JMeterReportTask>("jmeterReport") {
  jmxFile.set("test.jmx")
  dependsOn("runJMeter")
}
----
if you now execute `jmeterReport`, `runJMeter` get executed first if required
2. Or let the 'run' task always generate a report with `generateReport` flag
+
[source,kotlin]
----
register<JMeterRunTask>("runTest") {
  jmxFile.set("Test.jmx")
  generateReport = true
}
----
[TIP,title=Tip]
If you are going to rerun the task without cleaning outputs you will get an error because the report already exists. In such cases just enable the `deleteResults` property

=== Want to modify the jmx-Script with jmeter?
No problem, just add the following task to your build-script
[source,kotlin]
----
tasks {
  register<JMeterGuiTask>("edit") {
    jmxFile.set("test.jmx")
  }
}
----
And back to CLI
[source,shell script]
----
root> gradlew edit
----
As an alternative, if you don't want to clutter your tasks-section, you can use the `jmeter`-extension
[source,kotlin]
----
jmeter {
  withGuiTask("edit") {
    jmxFile.set("test.jmx")
  }
}
----

== Configure jmeter
As said in the prelude, this plugin is designed to be as flexible as possible.+
By that, the used jmeter runner artifact as well as plugins or libraries aren't hardwired but can be configured.


== Configure the runner
You can easily configure not only the version but also its coordinates. All this can be done through the `jmeter.tool` property. +
[source,kotlin]
----
jmeter {
  tool {
    group // <.>
    name // <.>
    version // <.>
    mainConfigureClosure // <.>
    mainClass // <.>

    jmeterPropertyFile // <.>
    reportTemplateFolder // <.>
    logConfig // <.>
    reportGeneratorPropertyFile // <.>
    saveServicePropertyFile // <.>
    upgradePropertyFile // <.>
  }
}
----
[%collapsible%]
====
<1> the group-id of the jmeter-runner
<2> the name (artifact-id) of the jmeter-runner
<3> the version of the jmeter-runner
<4> a closure/lambda to configure the dependency any further
<5> the main class used to execute the jmeter runner
<6> jmeters default property file
<7> default report template folder required by report tasks
<8> the log configuration used by jmeter
<9> the properties used by report tasks
<10> jmeter internal properties file, required to run
<11> jmeter internal properties file, required to run
====
[TIP,title=Tips]
====
1. If you need a different version of jmeter, download it from official jmeter site and copy the required files to your project.
2. If you change the tool version, it might be very likely that you also have to change most of the 'configuration files'
====

=== Extending runner
Because the runner itself is quite useless without any plugins this plugin 

In addition, you can add additional jmeter plugins or support libraries.+
This can be achieved using
[source,kotlin]
----
dependencies {
  jmeterPlugin("org.jmeter:a-plugin:1.2.3") // <.>
  jmeterLibrary("org.apache:commons-lang3:1.2.3") // <.>
}
----
<1> Resolves the 'a-plugin' and puts its artifact into `/lib/ext`, transitive dependencies will be put to `lib` directory.
<2> Resolves the 'commons-lang' artifact and puts its artifact, and all its transitive dependencies, under `/lib` directory.

[WARNING,title=Internal only]
====
Within an IDE with autocomplete, you may also notice the `jmeterRunner` dependency handler. This is for internal use only! Please use the respective `jmeter.tool` properties to configure the runner.
====
