name: "Build"

on:
  push:
    branches:
      - main
      - develop
      - issues/**

jobs:
  staticDetektCheck:
    name: "Detekt - static check"
    runs-on: ubuntu-latest
    steps:
      - name: "Check out sources"
        uses: actions/checkout@v2

      - name: "Detekt"
        uses: burrunan/gradle-cache-action@v1
        with:
          remote-build-cache-proxy-enabled: false
          save-local-build-cache: false
          arguments: detekt

      - name: "Upload detekt report"
        uses: actions/upload-artifact@v2
        with:
          name: detektReport
          path: build/reports/detekt

  licenceCheck:
    name: "Fossa licence analyze - static check"
    runs-on: ubuntu-latest
    steps:
      - name: "Check out sources"
        uses: actions/checkout@v2

      - name: "Fossa analyze"
        uses: fossas/fossa-action@v1
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}

      - name: "Fossa test"
        uses: fossas/fossa-action@v1
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}
          run-tests: true

  compile:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out sources"
        uses: actions/checkout@v2

      - name: "Compile"
        uses: burrunan/gradle-cache-action@v1
        with:
          remote-build-cache-proxy-enabled: false
          arguments: classes

  validatePlugin:
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - name: "Check out sources"
        uses: actions/checkout@v2

      - name: "Validate plugin"
        uses: burrunan/gradle-cache-action@v1
        with:
          remote-build-cache-proxy-enabled: false
          arguments: validatePlugins

  unitTest:
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - name: "Check out sources"
        uses: actions/checkout@v2

      - name: "Unit test cache"
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/build/reports/jacoco/**
          key: ${{ runner.os }}-test-${{ github.run_id }}

      - name: "Unit test"
        uses: burrunan/gradle-cache-action@v1
        with:
          remote-build-cache-proxy-enabled: false
          arguments: |
            test
            jacocoTestReport

      - name: "Publish Unit Test Results"
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          check_name: "Unit test results"
          files: build/test-results/**/*.xml

      - name: "Upload unit test report"
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: unitTestReport
          path: build/reports/tests/test

  functionalGroovyTest:
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - name: "Check out sources"
        uses: actions/checkout@v2

      - name: "Functional test cache"
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/build/reports/jacoco/**
          key: ${{ runner.os }}-funcGroovyTest-${{ github.run_id }}

      - name: "Functional groovy tests"
        uses: burrunan/gradle-cache-action@v1
        with:
          remote-build-cache-proxy-enabled: false
          arguments: |
            functionalGroovyTest
            jacocoGroovyReport

      - name: "Publish functional groovy test results"
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          check_name: "Functional groovy test results"
          files: build/test-results/functionalGroovyTest/*.xml

      - name: "Upload functional groovy test report"
        uses: actions/upload-artifact@v2
        if: always()
        with:
         name: functionalGroovyTestReport
         path: build/reports/tests/functionalGroovyTest

  functionalKotlinTest:
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - name: "Check out sources"
        uses: actions/checkout@v2

      - name: "Functional kotlin test cache"
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/build/reports/jacoco/**
          key: ${{ runner.os }}-funcKotlinTest-${{ github.run_id }}

      - name: "Functional kotlin tests"
        uses: burrunan/gradle-cache-action@v1
        with:
          remote-build-cache-proxy-enabled: false
          arguments: |
            functionalKotlinTest
            jacocoKotlinReport

      - name: "Publish functional kotlin test results"
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          check_name: "Functional kotlin test results"
          files: build/test-results/functionaKotlinTest/*.xml

      - name: "Upload functional kotlin test report"
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: functionalKotlinTestReport
          path: build/reports/tests/functionalKotlinTest

  report:
    runs-on: ubuntu-latest
    needs:
      - unitTest
      - functionalGroovyTest
      - functionalKotlinTest
    steps:
      - name: "Check out sources"
        uses: actions/checkout@v2

      - name: "Load test cache"
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/build/reports/jacoco/**
          key: ${{ runner.os }}-test-${{ github.run_id }}

      - name: "Load functional groovy test cache"
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/build/reports/jacoco/**
          key: ${{ runner.os }}-funcGroovyTest-${{ github.run_id }}

      - name: "Load functional kotlin test cache"
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/build/reports/jacoco/**
          key: ${{ runner.os }}-funcKotlinTest-${{ github.run_id }}

      - name: "Publish Report"
        uses: codecov/codecov-action@v2

  publishSnapshot:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.ref == 'develop'
    needs:
      - report
      - licenceCheck
    steps:
      - name: "Check out sources"
        uses: actions/checkout@v2

      - name: "Load compile cache"
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/build/**
          key: ${{ runner.os }}-compile-${{ github.run_id }}

      - name: "Publish"
        uses: burrunan/gradle-cache-action@v1
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ github.token }}
        with:
          remote-build-cache-proxy-enabled: false
          save-local-build-cache: false
          arguments: publish
